### ISSUE TITLE
Provide serializer for typesafe config

### ISSUE THREAD

**Issue by kretes** [twitter/chill#201]
I verified that such a code

```
val os = new ByteArrayOutputStream()
      val instantiator = new ScalaKryoInstantiator
      instantiator.setRegistrationRequired(false)
      val kryo: Kryo = instantiator.newKryo()
      val original: Config = ConfigFactory.load
      kryo.writeObject(new OutputChunked(os),original)
      val read: Config = kryo.readObject(new InputChunked(new ByteArrayInputStream(os.toByteArray)),classOf[Config])
```

with chill and typesafe config https://github.com/typesafehub/config on classpath does not work, but fails:

``` com.typesafe.config.Config
java.lang.InstantiationError: com.typesafe.config.Config
    at sun.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
    at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:56)
    at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1065)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:228)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:217)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:626)
```

**Comment by koertkuipers** [comment]
interesting idea. we have typesafe configs all over the place as well. we keep em out of classes because they dont serialize, but then we ran into the situation that when you put then in companion objects they come out "on the other side" incorrectly because application.conf is no longer on the classpath...
