### ISSUE TITLE
Running a Scalding job produces an error

### ISSUE THREAD

**Issue by danosipov** [twitter/chill#207]
```
2014-11-21 18:55:39,818 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.NoSuchMethodError: scala.collection.immutable.ListSet$.empty()Lscala/collection/immutable/ListSet;
	at com.twitter.chill.ScalaCollectionsRegistrar.apply(ScalaKryoInstantiator.scala:130)
	at com.twitter.chill.AllScalaRegistrar.apply(ScalaKryoInstantiator.scala:176)
	at com.twitter.chill.ScalaKryoInstantiator.newKryo(ScalaKryoInstantiator.scala:90)
	at com.twitter.scalding.serialization.KryoHadoop.newKryo(KryoHadoop.scala:58)
	at com.twitter.chill.config.ConfiguredInstantiator.newKryo(ConfiguredInstantiator.java:78)
	at com.twitter.chill.hadoop.KryoSerialization.setConf(KryoSerialization.java:70)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:73)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
	at org.apache.hadoop.io.serializer.SerializationFactory.add(SerializationFactory.java:72)
	at org.apache.hadoop.io.serializer.SerializationFactory.<init>(SerializationFactory.java:63)
	at org.apache.hadoop.mapred.MapTask.getSplitDetails(MapTask.java:368)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:404)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
```

I'm using Scalding 0.11.2 with Scala 2.10.3 - its probably a version conflict, but I don't know where the issue is.

**Comment by danosipov** [comment]
Related discussion: https://groups.google.com/forum/#!topic/cascading-user/sZc1ftd9Cr4

**Comment by johnynek** [comment]
So, the issue in the discussion says that Amazon put scala 2.11 on the path, but the user was using scala 2.10. That is going to break. You need to have only one version on the class path. We have scala 2.11 builds for all the Twitter stuff, so you just need to upgrade.

**Comment by johnynek** [comment]
@danosipov I'm going to close this. Reopen if you think it is not solved.
