### ISSUE TITLE
NullPointer after reloading org.joda.time.LocalDate

### ISSUE THREAD

**Issue by alltonp** [twitter/chill#226]
Hi, I'm new to chill, so apologies if this is a dumb question.

When reloading an object that contains a joda LocalDate I get a null pointer. It looks as if the deserialisation works, the exception is only thrown when I try to access the object, in this case the println.

Do I need to do something special for LocalDates?

Code sample and stacktrace below

Many thanks,

Paul

```
object ChillSpike extends App {
  import com.twitter.chill.{KryoPool, ScalaKryoInstantiator}
  import org.joda.time.LocalDate

  case class Example(localDate: LocalDate)

  val kryo = KryoPool.withByteArrayOutputStream(10, new ScalaKryoInstantiator())

  val instance = Example(new LocalDate())
  val bytes = kryo.toBytesWithClass(instance)
  val reloaded = kryo.fromBytes(bytes)
  //all okay ... until here
  println(reloaded)
}
```

```
Exception in thread "main" java.lang.NullPointerException
	at org.joda.time.LocalDate.isSupported(LocalDate.java:577)
	at org.joda.time.format.DateTimeFormatterBuilder$PaddedNumber.printTo(DateTimeFormatterBuilder.java:1434)
	at org.joda.time.format.DateTimeFormatterBuilder$Composite.printTo(DateTimeFormatterBuilder.java:2446)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:609)
	at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:663)
	at org.joda.time.LocalDate.toString(LocalDate.java:1832)
	at java.lang.String.valueOf(String.java:2982)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:200)
	at scala.collection.TraversableOnce$$anonfun$addString$1.apply(TraversableOnce.scala:344)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:342)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1202)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:308)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1202)
	at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:166)
```

**Comment by alltonp** [comment]
Forgot to say, this was using chill 0.5.2 and java 7 and 8.

**Comment by alltonp** [comment]
I managed to find the following serialiser, which looks like it could work - but how do I hook it into the Kryo config?

~~~
  import com.esotericsoftware.kryo.Serializer

  class LocalDateSerializer extends Serializer[LocalDate] with java.io.Serializable {
    override def write(kryo: Kryo, output: Output, obj: LocalDate) {
      output.writeInt(obj.getYear())
      output.writeInt(obj.getMonthOfYear())
      output.writeInt(obj.getDayOfMonth())
    }

    override def read(kryo: Kryo, input: Input, typeClass: Class[LocalDate]) : LocalDate = {
      new LocalDate(input.readInt(), input.readInt(), input.readInt());
    }
  }
~~~

**Comment by profic** [comment]
Kryo kryo = new Kryo();
kryo.addDefaultSerializer(LocalDate.class, localDateSerializer);

good luck

**Comment by alltonp** [comment]
Hi,

Thanks for responding. 

I'm using the scala 'KryoPool' and there doesn't appear to be any mechanism for registering serialisers. I did look at using Kryo directly but it was too low level for what I wanted, so I ended up copying the KryoPool source code and exposing a way to make it regsiterable.

The result is as follows, it's not very elegant but works for me ...

```
import java.io.{ByteArrayOutputStream, IOException, OutputStream}

import com.esotericsoftware.kryo.io.{Input, Output}
import com.esotericsoftware.kryo.{Kryo, Registration, Serializer}
import com.twitter.chill.{KryoInstantiator, KryoPool, SerDeState}

trait Regsiterable[T] {
  def register(kryo: Kryo): Registration
}

case class ClassAndSerializer[T](clazz: Class[T], serializer: Serializer[T]) extends Regsiterable[T] {
  override def register(kryo: Kryo) = kryo.register(clazz, serializer)
}

object RegisteringKryoPool {
  def withByteArrayOutputStream(poolSize: Int, ki: KryoInstantiator, regsiterables: Seq[Regsiterable[_ <: Any]]) = {
    new KryoPool(poolSize) {
      protected def newInstance: SerDeState = {
        val kryo = ki.newKryo

        regsiterables.map(r => r.register(kryo))

        new SerDeState(kryo, new Input, new Output(new ByteArrayOutputStream)) {
          override def clear() {
            super.clear()
            val byteStream = output.getOutputStream.asInstanceOf[ByteArrayOutputStream]
            byteStream.reset()
          }

          override def outputToBytes: Array[Byte] = {
            output.flush()
            val byteStream = output.getOutputStream.asInstanceOf[ByteArrayOutputStream]
            byteStream.toByteArray
          }

          @throws(classOf[IOException])
          override def writeOutputTo(os: OutputStream) {
            output.flush()
            val byteStream = output.getOutputStream.asInstanceOf[ByteArrayOutputStream]
            byteStream.writeTo(os)
          }
        }
      }
    }
  }
}
```

The client code is then:

```
  val kryo = RegisteringKryoPool.withByteArrayOutputStream(10,
    new ScalaKryoInstantiator(),
    Seq(ClassAndSerializer(classOf[LocalDate], new LocalDateSerializer()))
  )
```
