### ISSUE TITLE
Serializing custom class Object causes "ConfigObject is immutable, you can't call Map.put" error

### ISSUE THREAD

**Issue by ailesgrise** [twitter/chill#265]
I was using twitter chill to Serialize my custom class object and got the following error stack

```
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
[error] Serialization trace:
[error] object (com.typesafe.config.impl.SimpleConfig)
[error] config (CpdLogic$CpdLogicCore)
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
Serialization trace:
object (com.typesafe.config.impl.SimpleConfig)
config (CpdLogic$CpdLogicCore)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:107)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:98)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at EnhancedCod$.main(EnhancedCod.scala:97)
    at EnhancedCod.main(EnhancedCod.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
    at com.typesafe.config.impl.AbstractConfigObject.weAreImmutable(AbstractConfigObject.java:193)
    at com.typesafe.config.impl.AbstractConfigObject.put(AbstractConfigObject.java:204)
    at com.typesafe.config.impl.AbstractConfigObject.put(AbstractConfigObject.java:20)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:162)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
    at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:107)
    at EnhancedCod$$anonfun$6.apply(EnhancedCod.scala:98)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at EnhancedCod$.main(EnhancedCod.scala:97)
    at EnhancedCod.main(EnhancedCod.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
```

My class object does take a typesafe ConfigObject as an input for construction and the configObject is immutable. 

I have no problem writing the object but when I read it again, I get the aforementioned error. 

I am using Scala 2.10.5 using com.twitter chill version 0.8.0.

**Comment by magro** [comment]
Cross post: EsotericSoftware/kryo#472 ;-)

**Comment by johnynek** [comment]
did you try chill 0.8.1:

https://github.com/twitter/chill/releases/tag/v0.8.1

it has support for immutable java maps.

**Comment by ailesgrise** [comment]
Chill 0.9.2 still doesn't seem to work. I still get the same error message.

**Comment by johnynek** [comment]
I guess the solution is to implement a serializer for Config and register that.

**Comment by ailesgrise** [comment]
Right, I'll give that a try thank you.

**Comment by agnaldo4j** [comment]
Hi @ailesgrise and @johnynek 
Today I tried upgrading to Akka 2.5.11 and got the same error.
```
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
Serialization trace:
object (com.typesafe.config.impl.SimpleConfig)
configOfJoiningNode (akka.cluster.InternalClusterAction$InitJoin)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
```
@ailesgrise, Have you implemented the Serializer? Doing it solved the problem?

@johnynek Do you think to implement this serializer in the project by default?

**Comment by johnynek** [comment]
I would be happy to accept a PR but I don’t use Akka, nor does Twitter, so I don’t think any of the usual contributors will get to it soon.

I would welcome a PR from you thought! :)

**Comment by agnaldo4j** [comment]
Hi @johnynek I found the problem, we configure Akka cluster messages to be serialized by kryo but the correct config is to use the default Akka serialization for it.

thanks
