### ISSUE TITLE
Not implemented method in Java8ClosureRegistrar

### ISSUE THREAD

**Issue by Slav4ik** [twitter/chill#328]
`
java.lang.NoSuchMethodError: com.twitter.chill.java.Java8ClosureRegistrar.areOnJava8()Z
	at com.twitter.chill.KryoBase.isJavaLambda(KryoBase.scala:47)
	at com.twitter.chill.KryoBase.getRegistration(KryoBase.scala:50)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:79)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:488)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:593)
	at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:274)
	at org.apache.flink.api.java.typeutils.runtime.PojoSerializer.serialize(PojoSerializer.java:357)
	at org.apache.flink.api.java.typeutils.runtime.PojoSerializer.serialize(PojoSerializer.java:357)
	at org.apache.flink.api.common.typeutils.base.GenericArraySerializer.serialize(GenericArraySerializer.java:120)
	at org.apache.flink.api.common.typeutils.base.GenericArraySerializer.serialize(GenericArraySerializer.java:36)
	at org.apache.flink.streaming.api.functions.source.FromElementsFunction.<init>(FromElementsFunction.java:88)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.fromCollection(StreamExecutionEnvironment.java:814)
`

**Comment by Slav4ik** [comment]
I might have been using incompatible versions between chill-protobuf and other. Please validate it works on the current versions

**Comment by vinodmehra** [comment]
Were you able to find a solution for this?

**Comment by Slav4ik** [comment]
unfortunately, I left that project and don't remember what was the solution. 
I think I ended up using the api in another manner.

**Comment by johnynek** [comment]
no such method error is a binary incompatibility problem. You seem to have incorrect versions of chill on the classpath.

This happens when you have two dependencies that use different versions and the wrong one gets selected.

I don't think we can fix this in the library itself.  Please reopen if you feel this is a bug we can fix.

**Comment by DryLemon928** [comment]
![图片](https://user-images.githubusercontent.com/28866957/167847725-2345e9b1-be31-455f-8c9e-f6684b29ed3a.png)
1.find the conflicts in pom.xml
2.exclude one of them
