### ISSUE TITLE
java.lang.IllegalArgumentException: classLoader cannot be null

### ISSUE THREAD

**Issue by rajeshkalaria80** [twitter/chill#684]
Describe the bug
We are using chill-akka for serialization/deserialization of akka remote messages. In tests, we have turned on "akka.actor.serialize-messages" to catch any such issues during development only.

We have one or two uni tests which fails intermittently with below mentioned exception stack trace. In my troubleshooting, what I have found is that in `ScalaKryoInstantiator.scala`, it fails in class `EmptyScalaKryoInstantiator`, when it is executing below statement

`k.setClassLoader(classLoader)`

[ERROR] [15:30:34.461] [lt-dispatcher-3] [a.a.t.i.a.ActorAdapter:$anonfun$applyOrElse$1:77] [akkaAddress=akka://verity@127.0.0.1:2000, sourceThread=pool-20-thread-8, akkaSource=akka://verity/user/$a, sourceActorSystem=verity, akkaTimestamp=10:00:34.446UTC] -- swallowing exception during message sendakka.actor.dungeon.SerializationCheckFailedException: Failed to serialize and deserialize message of type com.evernym.verity.msgoutbox.outbox.msg_store.MsgStore$Commands$GetPayload for testing. To avoid this error, either disable 'akka.actor.serialize-messages', mark the message with 'akka.actor.NoSerializationVerificationNeeded', or configure serialization to support this message	at akka.actor.dungeon.SerializationCheckFailedException$.apply(Dispatch.scala:27)	
at akka.actor.dungeon.Dispatch.serializeAndDeserialize(Dispatch.scala:183)	
at akka.actor.dungeon.Dispatch.sendMessage(Dispatch.scala:160)	
at akka.actor.dungeon.Dispatch.sendMessage$(Dispatch.scala:157)	
at akka.actor.ActorCell.sendMessage(ActorCell.scala:411)	
at akka.actor.Cell.sendMessage(ActorCell.scala:327)	
at akka.actor.Cell.sendMessage$(ActorCell.scala:326)	
at akka.actor.ActorCell.sendMessage(ActorCell.scala:411)	
at akka.actor.LocalActorRef.$bang(ActorRef.scala:448)	
at akka.actor.typed.internal.adapter.ActorRefAdapter.tell(ActorRefAdapter.scala:27)	
at akka.actor.typed.RecipientRef$RecipientRefOps$.$bang$extension(ActorRef.scala:133)	
at akka.actor.typed.scaladsl.AskPattern$PromiseRef.ask(AskPattern.scala:161)	
at akka.actor.typed.scaladsl.AskPattern$.akka$actor$typed$scaladsl$AskPattern$$askClassic(AskPattern.scala:170)	
at akka.actor.typed.scaladsl.AskPattern$Askable$.ask$extension(AskPattern.scala:111)	
at com.evernym.verity.msgoutbox.message_repository.MessageRepositoryImpl.$anonfun$read$4(MessageRepositoryImpl.scala:43)	
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	
at java.base/java.lang.Thread.run(Thread.java:829)
**Caused by:** java.lang.RuntimeException: java.lang.IllegalArgumentException: **classLoader cannot be null.**	
at com.twitter.chill.ResourcePool.borrow(ResourcePool.java:44)	
at com.twitter.chill.KryoPool.toBytesWithClass(KryoPool.java:114)	
at com.twitter.chill.akka.AkkaSerializer.toBinary(AkkaSerializer.scala:70)	
at akka.actor.dungeon.Dispatch.serializeAndDeserializePayload(Dispatch.scala:203)	
at akka.actor.dungeon.Dispatch.serializeAndDeserialize(Dispatch.scala:181)	... 17 common frames omitted
**Caused by:** java.lang.IllegalArgumentException: **classLoader cannot be null**.	
at com.esotericsoftware.kryo.Kryo.setClassLoader(Kryo.java:1028)	
at com.twitter.chill.EmptyScalaKryoInstantiator.newKryo(**ScalaKryoInstantiator.scala:67**)	
at com.twitter.chill.ScalaKryoInstantiator.newKryo(ScalaKryoInstantiator.scala:97)	
at com.twitter.chill.ScalaKryoInstantiator.newKryo(ScalaKryoInstantiator.scala:95)	
at com.twitter.chill.KryoInstantiator$6.newKryo(KryoInstantiator.java:101)	
at com.twitter.chill.KryoPool$2.newInstance(KryoPool.java:59)	
at com.twitter.chill.KryoPool$2.newInstance(KryoPool.java:57)	
at com.twitter.chill.ResourcePool.borrow(ResourcePool.java:37)	... 21 common frames omitted 

To Reproduce
So far I don't have any simple code snippet to reproduce it, the unit test fails intermittently

Expected behavior
A check should be performed on the `classLoader` variable to make sure it is not null and then only it should call `k.setClassLoader(classLoader)`

Environment
We are using scalaVersion "**2.13**.8", akka libraries "2.6.18" and chill-akka "0.10.0" in a Scala project on Ubuntu 18.04 machine.

Additional context
n/a

**Comment by rajeshkalaria80** [comment]
Here is PR to fix this issue: https://github.com/twitter/chill/pull/685.

**Comment by regadas** [comment]
Thanks for the report and PR; closed vis #685
